language: c

env:
  global:
    - "HOST_IP=$(/sbin/ifconfig venet0:0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
    - DOCKER_HOST=tcp://$HOST_IP:2375
    - DOCKER_PORT_RANGE=2400:2500
    - SLIRP_PORTS=$(seq 2375 2500)

before_install:
  - sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d
  - sudo touch /usr/local/bin/docker-compose
  - sudo chmod +wx /usr/local/bin/docker-compose

install:
  - sudo apt-get -qqy update
  - sudo apt-get -qqy install lxc lxc-docker-1.2.0 slirp
  - sudo usermod -aG docker "$USER"
  - curl -L https://github.com/docker/compose/releases/download/1.2.0rc2/docker-compose-`uname -s`-`uname -m` > ./docker-compose
  - chmod +x ./docker-compose
  - git clone git://github.com/cptactionhank/sekexe

before_script:
  - "sekexe/run 'mount -t tmpfs -o size=8g tmpfs /var/lib/docker && docker -d -H tcp://0.0.0.0:2375' &"
  - "while ! docker info &> /dev/null ; do sleep 1; done"

script:
  - docker version
  - echo $PATH
#  - docker pull zaporylie/drupal-dev
#  - docker pull mysql:5.5
  - ./docker-compose --file=docker-compose-test.yml up
  - docker ps -a
