# Run this configuration if you need xdebug
# That's almost the same file as production with only few changes.
# Documentation available in docker-compose-production file.
#
# @author zaporylie <jakub@piaseccy.pl>

datamysql:
  image: mysql:5.5
  entrypoint: /bin/echo
  command: MySQL data-only container

datadrupal:
  image: zaporylie/drupal-dev
  volumes:
    - ./:/app
  entrypoint: /bin/echo
  command: APP data-only container

mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: secret_password
  volumes_from:
    - datamysql

drupal:
  image: zaporylie/drupal-dev
  volumes_from:
    - datadrupal
  volumes:
    - ./scripts/pre-install.sh:/root/pre-install.sh
    - ./scripts/post-install.sh:/root/post-install.sh
    # - ~/.ssh:/root/.ssh
    # - path/to/your/file:/var/backups/db.sql
  links:
    - mysql:mysql
  environment:
    DRUPAL_DB: drupal
    DRUPAL_DB_USER: drupal
    DRUPAL_DB_PASSWORD: drupal
    DRUPAL_PROFILE: minimal
    DRUPAL_SUBDIR: default
    DRUPAL_MAJOR_VERSION: 7
    DRUPAL_DOWNLOAD_METHOD: drush
    METHOD: auto
    MYSQL_HOST_NAME: mysql
    VIRTUAL_HOST: drupal1.*
    SYNC_METHOD: AUTO
    SYNC_SOURCE: staging
    ENVIRONMENT: DEV
  ports:
    - "80"
    - "22"
    - "9000"
